[package]
name = "mev-build-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "api", "serde_json"]
api = ["axum", "beacon-api-client", "tracing"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version =  "0.5.4", optional = true }
tracing = { version = "0.1", optional = true }
async-trait = "0.1.53"

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
thiserror = "1.0.30"
url = { version = "2.2.2", default-features = false }

ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus" }
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs" }
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client", optional = true }
